name: calc

on:
  push:
    branches:
      - main
    files:
      - 'scripts/**'
      - 'public/data/**'
      - '.github/workflows/calc.yml'
    paths-ignore:
      - '.github/workflows/static.yml'
      - 'js/**'
      - 'public/images/**'
      - '.gitignore'
      - 'favicon.ico'
      - 'index.html'
      - 'style.css'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run Calculation Script
        run: |
          python scripts/calc.py \
            -c public/data/character_card.csv \
            -b public/data/card_give_characteristic.csv \
            -g public/data/card_give_characteristic_grow_list.csv \
            -t public/data/characteristics_normal.csv \
            -o output/

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin artifacts || true
          git checkout artifacts 2>/dev/null || git checkout -b artifacts

          rm -rf solutions/
          mv output/ solutions/

          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo $CURRENT_DATE > data-last-update

          git add solutions/ data-last-update
          git commit -m "Auto-generated solutions from GitHub Actions" || echo "No changes to commit"
          git push origin artifacts
