name: calc

on:
  push:
    branches:
      - public # only run on the public branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run Calculation Script
        run: |
          python scripts/calc.py \
            -c public/data/character_card.csv \
            -b public/data/card_give_characteristic.csv \
            -g public/data/card_give_characteristic_grow_list.csv \
            -t public/data/characteristics_normal.csv \
            -o public/solutions/

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -B public

          git add public/solutions/
          git commit -m "Auto-generated solutions from GitHub Actions" || echo "No changes to commit"
          git push origin public
