name: Calculate Solutions

on:
  push:
    branches:
      - main
    files:
      - 'scripts/**'
      - 'public/data/**'
      - '.github/workflows/calc.yml'
    paths-ignore:
      - '.github/workflows/static.yml'
      - '.github/workflows/last-update.yml'
      - 'js/**'
      - 'public/images/**'
      - '.gitignore'
      - 'favicon.ico'
      - 'index.html'
      - 'style.css'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run Calculation Script
        run: |
          python scripts/calc.py \
            -c public/data/character_card.csv \
            -b public/data/card_give_characteristic.csv \
            -g public/data/card_give_characteristic_grow_list.csv \
            -t public/data/characteristics_normal.csv \
            -o output/

      - name: Get Last Modified Date from GitHub API
        id: get_last_modified
        run: |
          # Get the file list of public/data directory using GitHub API without auth
          response=$(curl -s "https://api.github.com/repos/a1sareru/shoot300k/contents/public/data")
          
          # Extract last modified date from the response (assuming file list is returned)
          last_modified=$(echo "$response" | jq -r 'map(select(.type == "file")) | map(.git_url) | .[0]' | \
            xargs -I {} curl -s "{}" | jq -r .commit.committer.date | sort | tail -n 1)

          echo "Last modified date: $last_modified"
          echo "::set-output name=last_modified::$last_modified"

      - name: Update Last Modified Date File
        run: |
          # Update the data-last-update file with the latest modification date
          echo "${{ steps.get_last_modified.outputs.last_modified }}" > data-last-update

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin artifacts || true
          git checkout artifacts 2>/dev/null || git checkout -b artifacts

          rm -rf solutions/
          mv output/ solutions/

          git add solutions/ data-last-update
          git commit -m "Auto-generated solutions from GitHub Actions" || echo "No changes to commit"
          git push origin artifacts
