name: Enumerate solutions when data is updated

on:
  workflow_run:
    workflows: ["maintain"]
    types:
      - completed
  push:
    branches:
      - main
    files:
      - "scripts/**"
      - "public/data/**"
      - ".github/workflows/calc.yml"
    paths-ignore:
      - ".github/workflows/maintain.yml"
      - ".github/workflows/static.yml"
      - "css/**"
      - "deprecate/**"
      - "js/**"
      - "lang/**"
      - "public/images/**"
      - "scripts/maintain-log/**"
      - "static/**"
      - ".gitignore"
      - "index.html"
      - "site.webmanifest"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run Calculation Script
        run: |
          python scripts/calc.py \
            -c public/data/character_card.csv \
            -b public/data/card_give_characteristic.csv \
            -g public/data/card_give_characteristic_grow_list.csv \
            -t public/data/characteristics_normal.csv \
            -o output/

      - name: Get Last Modified Date from GitHub API
        id: get_last_modified
        run: |
          # Set file path
          FILE_PATH="public/data/card_give_characteristic.csv"

          # Get commit history for the file
          commit_data=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?path=${FILE_PATH}")

          # Extract last modified date from the most recent commit to %Y-%m-%d format
          last_modified=$(echo "$commit_data" | jq -r '.[0].commit.committer.date' | cut -d 'T' -f 1)

          # Output the last modified date
          echo "Last modified date of $FILE_PATH: $last_modified"

          # Update the data-last-update file with the latest modification date
          echo "$last_modified" > data-last-update-tmp

          # Update the repo-last-update file with the latest modification date
          echo "$last_modified" > repo-last-update-tmp

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin artifacts || true
          git checkout artifacts 2>/dev/null || git checkout -b artifacts

          rm -rf solutions/ data-last-update repo-last-update
          mv output/ solutions/
          mv data-last-update-tmp data-last-update
          mv repo-last-update-tmp repo-last-update

          git add solutions/ data-last-update repo-last-update
          git commit -m "Auto-generated solutions from GitHub Actions" || echo "No changes to commit"
          git push origin artifacts
