name: maintain

on:
  schedule:
    - cron: "0 7 */5 * *"   # Every 5 days at 07:00 UTC
  workflow_dispatch:        # Manual trigger is also possible

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run maintain.py
        run: python scripts/maintain.py
      # this subtask is just for debug
      - name: Who am I
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/user

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add public scripts
          git commit -m "Auto update data" || echo "No changes to commit"
          git push